src/Entity/Links.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LinksRepository")
 */
class Links
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="text")
     */
    private $Cible;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCible(): ?string
    {
        return $this->Cible;
    }

    public function setCible(string $Cible): self
    {
        $this->Cible = $Cible;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Form/AddLinkType.php
<?php

namespace App\Form;

use App\Entity\Links;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddLinkType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Name')
            ->add('Cible')
            ->add('Description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Links::class,
        ]);
    }
}

src/Controller/LinksController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\Links;
use App\Repository\LinksRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Form\AddLinkType;

/** controller pour afficher, rajouter et éditer les liens */
class LinksController extends Controller
{
/** Méthode pour afficher tous les liens sur page accueil */
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $em = $this->getDoctrine()->getManager();
        $links = $em->getRepository(Links::class)->findAll();

        return $this->render('links/index.html.twig', [
            'links' => $links,
        ]);
    }

/** Méthode pour afficher le détail d'un lien */
    /**
     * @Route("/view/{id}", name="view")
     */
    public function view(Links $link)
    {
        return $this->render('links/view.html.twig', [
            'link'  =>  $link
        ]);
    }

/** Méthode pour rajouter un lien dans mysql
 *  si ok redirection vers page accueil
 */
    /**
     * @Route("/add", name="add")
     */
    public function add(Request $request)
    {
        $link = new Links();
        $form = $this->createForm(AddLinkType::class, $link);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
	        $em = $this->getDoctrine()->getManager();
	        $em->persist($link);
	        $em->flush();

	        return $this->redirectToRoute('home');
	    }

        return $this->render('links/add.html.twig', [
	        'form'  =>  $form->createView()
        ]);
    }

/** Méthode pour éditer le lien
 *  si ok redirection vers le détail du lien
 */
    /**
	 * @Route("/edit/{id}", name="edit")
	 */ 
	public function edit(Links $link, Request $request){
	    $form = $this->createForm(AddLinkType::class, $link);

	    $form->handleRequest($request);
	    
	    if($form->isSubmitted() && $form->isValid()){
	        $em = $this->getDoctrine()->getManager();
	        $em->persist($link);
	        $em->flush();

            return $this->render('links/view.html.twig', [
                'link'  =>  $link
            ]);
	    }

	    return $this->render('links/add.html.twig', [
	        'form'  =>  $form->createView()
	    ]);
    }
    
    /** Méthode pour effacer le lien
 *  si ok redirection vers page accueil
 */
    /**
	 * @Route("/erase/{id}", name="erase")
	 */ 
	public function erase(Links $link, Request $request){
	    $form = $this->createForm(AddLinkType::class, $link);

	    $form->handleRequest($request);
	    
	    if($form->isSubmitted() && $form->isValid()){
	        $em = $this->getDoctrine()->getManager();
	        $em->remove($link);
	        $em->flush();

            return $this->render('links/view.html.twig', [
                'link'  =>  $link
            ]);
	    }

	    return $this->render('links/erase.html.twig', [
	        'form'  =>  $form->createView()
	    ]);
	}
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        {# le titre de la page doit être rajouté avant le tiret #}
        <title>{% block title %}{% endblock %} - Zulgate</title>

        {% block stylesheets %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body>
        {# Header #}
        <div class="col-md-12 sticky-top bg-light shadow">
            <nav class="navbar">
                <a class="navbar-brand" href="/">Zulgate</a>
                <ul class="nav justify-content-end">
                    <li>
                        <a class="nav-link" href="#">
                            <i class="fa fa-envelope-o"></i>
                        </a>
                    </li>
                    <li>                            
                        <a class="nav-link" href="#">Se connecter</a>
                    </li>
                </ul>
            </nav>
        </div>
        {# Menu gauche #}
        <div class="row m-0">
            <div class="col-md-2 bg-light">
            <nav class="fixed-left d-none d-md-block bg-light sidebar pt-2 h-100">
                <div class="sidebar-sticky">
                    <ul class="nav">
                        <li class="sidebar-search mx-3">
                            <a class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Recherche...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="{{ path("add") }}">Rajouter un lien</a>
                        </li>
                    </ul>
                </div>            
            </nav>
            </div>
            {# contenant #}
            <div class="col-md-10 mr-0">
                <div class="container-fluid">
                  {% block body %}{% endblock %}
                </div>
            </div>
        </div>
        {# footer #}
        <footer class="footer bg-light font-weight-light">
            <div class="container">
                <p class="text-center mb-0" href="#">Crédit - Mentions</p>
            </div>
        </footer>
    
        {% block javascripts %}
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

templates/links/add.html.twig
{% extends 'base.html.twig' %}

{# le titre est rajouté devant - Zulgate #}
{% block title %}
    Edition du lien
{% endblock %}

{# Formulaire pour rajouter et éditer #}
{% block body %}

    <div class="col-md-6 my-3 float-left">
        <div class="form-group">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            {{ form_rest(form) }}
            <button type="submit" class="btn btn-primary">Valider</button>
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}

templates/links/erase.html.twig
{% extends 'base.html.twig' %}

{# le titre est rajouté devant - Zulgate #}
{% block title %}
    Effacer le lien
{% endblock %}

{% block body %}

    <div class="col-md-6 my-3 float-left">
        <div class="form-group">
            {{ form_start(form) }}
            {{ form_errors(form) }}
            {{ form_rest(form) }}
            <button type="submit" class="btn btn-outline-danger">Effacer</button>
            <a class="btn btn-outline-primary" href="/">Annuler</a>
            {{ form_end(form) }}           
        </div>        
    </div>

{% endblock %}

templates/links/index.html.twig
{% extends 'base.html.twig' %}

{# le titre est rajouté devant - Zulgate #}
{% block title %}
    Accueil
{% endblock %}

{# affichage de tous les liens en page d'accueil #}
{% block body %}
    <div class="row m-0">
        {% for link in links %}
            <div class="col-md-3 float-left">
                <div class="card border-secondary my-3">
                    <div class="card-header">
                        <a href="{{ link.cible }}" target="_blank">
                            {{ link.name }}
                        </a>
                    </div>
                    <div class="card-body">
                        <p class="card-text font-weight-light" href="{{ path("view", {id: link.id}) }}">
                                {{ link.description }}
                        </p>
                        <a class="btn btn-outline-primary btn-sm" href="{{ path("view", {id: link.id}) }}">Détail
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div> 
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">Précédent</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item">
            <a class="page-link" href="#">Suivant</a>
            </li>
        </ul>
    </nav>
    <br> 
{% endblock %}

templates/links/view.html.twig
{% extends 'base.html.twig' %}

{# le titre est rajouté devant - Zulgate #}
{% block title %}
    Détails du lien
{% endblock %}

{# Détail du lien #}
{% block body %}
    <div class="col-md-12">
        <div class="card border-secondary my-3">
            <div class="card-header">
                <h3>
                    {{ link.name }}
                </h3>
            </div>
            <div class="card-body">
                <p>
                    {{ link.description }}
                </p>
                <p>
                <a href="{{ link.cible }}" target="_blank">
                    {{ link.cible }}
                </a>
                <p>
                <p>
                <a class="btn btn-outline-primary" href="{{ path('edit', {id : link.id}) }}">
                    Editer
                </a>
                 <a class="btn btn btn-outline-danger" href="{{ path('erase', {id : link.id}) }}">
                    Effacer le lien
                </a>
                </p>
            </div>
        </div>
    </div>
    
{% endblock %}